before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: XFJcwsgovMZ0O2lg6q6/A+Lp8x165K/oz/cYbpU/rMEz5KG1hVoyug7fVNEP0v1MecS2EdXPVyzMxcTmNMc7f+Rrh/KF73YlaA1vSAd7AFT6pPlX86d7MRv7mF1FxfO8WW8UBwhB0ikrzi3hJnEBEIj3MxjAKph3PzaaQk/TWbuFiCWVW0Jv4aOruOqctgrasEPwjaFqITVI6BdX/IKme0llZ8AEhnrbaUNbKx8FhJuMVhXG55plIGH7TtOMNrGlb7dRUC62sc+BBKRB3KkWuble9DGO6+iSTAsluy75fc0iQAbHe+fmlqR2QNM1gwcTaBThkspidopM7YF5mSPBq0oU2RubIr/ws8AS5rh4QAPoW8QBJajaP4ASYXq1WNvllgWm24IBzFzMttyhS/0pIbSXsMXh2cnXDXKWMEWmjBT2Ky21Z4hpJnnyOXmI6iKMNgQKb4i+tevcpPtya5hcHdyYF/DrWK89JWphVnTtEPGhy3xWz531tzSHRSiCNUKNajiBjuLAs+7dYyauvnJbt9/HaoR2VOQkmXXLqyjk+XS5gS0cJR3eVVZofstseI/45eWoLlRQIiTBF4GnNM502eYlGmaWnKo0d8VC5/SrjuSp59shD3jvOLjjAxPOrilKOir6NNNU8vSbptjFen8j0C5gBKNUVy7PNVL8j9TTLBI= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
